--- 
title: "Statistical Computing Using R"
author: "Lily Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Preface

## What you will learn

This book introduces modern statistical computing for students with some experience with computer programming. It covers both programming concepts and statistical computing concepts. Programming concepts will include data manipulations, data structures, flow control, functions and variable scope, regular expressions, and matrix manipulations. You’ll learn how to get your data into R, get it into the most useful structure, transform it, visualize it and model it. You’ll learn how to use the grammar of graphics, literate programming, and reproducible research to save time. You’ll also learn how to manage cognitive resources to facilitate discoveries when wrangling, visualizing and exploring data. Statistical computing topics will focus on the tools that are useful for tackling modern data analysis problems and using statistical methods to extract meaning from data. 

## Acknowledgements

I am very appreciative of all the contributors to this immense open source project of R and R-Studio. I couldn’t have made this book without your contributions and the packages that you have developed. A special thanks go to [Dr. Guannan Wang](https://people.wm.edu/~gwang01/index.html) and Miss Zhiling Gu for their help with the book. I would also like to thank Yihui Xie [@xie2020bookdown] for his R Markdown package, which simplifies the writing of this book by having all content written in R Markdown.

## About the Author

Dr. Lily Wang is a tenured Professor of Statistics at Iowa State University. She received her Ph.D. in Statistics from Michigan State University in 2007. Prior to joining Iowa State in 2014, she was a tenure-track Assistant/tenured Associate Professor in the Department of Statistics at the University of Georgia 2007-2013/2013-2014. Her primary areas of research include developing cutting-edge statistical non/semi-parametric methods, statistical learning of large datasets with complex features, methodologies for functional data, imaging data, and spatiotemporal data, survey sampling, and the application of statistics to problems in economics, engineering, neuroimaging, epidemiology, environmental studies, and biomedical science. 
